import type { Metadata } from "next";
import MainHeader from "@/components/main-header";
import { Roboto_Mono } from "next/font/google";
import { Inter } from "next/font/google";
import "./globals.scss";

const roboto = Roboto_Mono({
  subsets: ["latin"],
  weight: ["400", "700"], // add weights as needed
});

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "700"], // add weights as needed
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className} ${inter.className}`}>
        <MainHeader />
        <main>
          <div className="container">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
